### ISSUE TITLE
Vagrant up results in: default: Warning: Connection timeout. Retrying...

### ISSUE THREAD

**Issue by rkoster** [adaptivdesign/devoku#1]
Saw following error message in the gui: `[ *** ] A start job is running for Raise network interfaces`

Fixed by adding `provider.customize ["modifyvm", :id, "--cableconnected1", "on"]` as suggested [here](https://github.com/chef/bento/issues/682#issuecomment-252381145).

**Comment by adaptivdesign** [comment]
Added this to the Odooku repo, will find underlying cause in this repo.
