### ISSUE TITLE
No buildpack when trying to build project

### ISSUE THREAD

**Issue by rkoster** [adaptivdesign/devoku#2]
When running `devoku build` I get the following error: 

```
vagrant@ubuntu:/vagrant$ devoku build
-----> Starting build
       Removing stale Docker containers and images
       Using local commit 80de9c3f51393902cac8ce408ca8f31224e0ae04
-----> Building slug
-----> Unable to select a buildpack
```

**Comment by rkoster** [comment]
fixed it by adding `export BUILDPACK_URL=https://github.com/adaptivdesign/odooku-buildpack` to `.devoku/.env`

**Comment by adaptivdesign** [comment]
did you run 'devoku env new` before building? Because this creates the needed .env file.

**Comment by rkoster** [comment]
yhea I did, but it used [.env.template](https://github.com/adaptivdesign/devoku/blob/master/include/.env.template) from the devoku repo which is missing `BUILDPACK_URL`, after I copied [.env.template](https://github.com/adaptivdesign/odooku/blob/master/.env.template) from the odooku project it all started working.

**Comment by adaptivdesign** [comment]
Ohh now I see, the misunderstanding :) Ok so let me explain:

- Devoku is a generic project, which is responsible for the adaptivdesign/devoku image. 
- Odooku uses Devoku to create a development environment for Odoo projects.
- You can use Devoku for any sort of Heroku project, not just Odooku

So you should indeed checkout Odooku and create your development environment based on that project. Only use the Devoku repo as an example and for docs.

**Comment by rkoster** [comment]
I see, makes sense 😄
